customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3_dev_0.8
  generator: "Rime::SwitcherSettings"
  modified_time: "Fri Mar 10 18:24:34 2023"
  rime_version: 1.8.5
patch:
  "menu/page_size": 7
  schema_list:
    - {schema: double_pinyin_flypy}
    - {schema: easy_en}
    - {schema: chaizi}