var:
  last_build_time: 1678360561
  option:
    simplification: true
  previously_selected_schema: double_pinyin_flypy
  schema_access_time:
    double_pinyin_flypy: 1678001912
    easy_en: 1678001897
    luna_pinyin: 1677906681
    luna_pinyin_simp: 1677757586
    terra_pinyin: 1677906586