customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Thu Jun 27 17:32:21 2019"
  rime_version: 1.5.3

patch:
  "style/display_tray_icon": false #是否显示右下角图标
  "style/horizontal": true #横排显示
  "style/font_face": "Microsoft YaHei" #字体
  "style/font_point": 14 #字体大小
  "style/inline_preedit": true # 嵌入式候选窗单行显示




  "style/layout/border_width": 0
  "style/layout/border": 0
  "style/layout/margin_x": 8 #候选字左右边距
  "style/layout/margin_y": 8 #候选字上下边距
  "style/layout/hilite_padding": 8 #候选字背景色色块高度 若想候选字背景色块无边界填充候选框，仅需其高度和候选字上下边距一致即可
  "style/layout/hilite_spacing": 3 # 序号和候选字之间的间隔
  "style/layout/spacing": 10 #不知道干嘛的+1，不清楚效果
  "style/layout/candidate_spacing": 12 # 候选字间隔
  "style/layout/round_corner": 0 #候选字背景色块圆角幅度



  "style/color_scheme": 西米露
  "preset_color_schemes/西米露":
    name: 西米露
    author: Loong
    back_color: 0x030303 #候选框 の 背景色
    border_color: 0x0A0A0A #候选框 の 边框颜色
    text_color: 0xFAFAFF #已选择字 の 文字颜色
    hilited_text_color: 0xFFFFFF #已选择字右侧拼音 の 文字颜色
    hilited_back_color: 0x4734D6 #已选择字右侧拼音 の 背景色
    hilited_candidate_text_color: 0xFFFFFF #候选字 の 颜色
    hilited_candidate_back_color: 0x4734D6 #候选字 の 背景色
    candidate_text_color: 0xFFFFFF #未候选字 の 颜色
    comment_text_color: 0xFCFCFC #未知效果